### ISSUE TITLE
2.8 release checklist

### ISSUE THREAD

**Issue by oldmud0** [AttorneyOnline/AO2-Client#160]
(GitHub erased my draft, so this is a shorter version than what I had originally written.)

2.8 has one of the most comprehensive set of changes ever made to AO, thanks to a merge with the Killing Fever Online client. I always get cold feet doing releases, since the process is lengthy, and allowing a bug to pass through means repeating the release process for a patch version.

The release process is about the same as any other release, with a few much-needed changes:

- Fixes for character INIs (_excluding_ proposed changes to the character roster)
- Addition of launcher to full manual download

### Last-minute issues

- Translations - there are a ton of untranslated strings, but it's probably best to just release as-is. (Speaking of which, perhaps images in themes should be localizable as well.)
- Minor visual issues in default theme:
  - Settings button looks off, since it's not an image like the adjacent "About" button.
  - Drop-down menus in the courtroom fall back to the Windows Classic theme due to a custom color being designated for them.
- Old themes freeze the client.

### General checklist

- [x] [Write release notes](https://hackmd.io/@oldmud0/H1fharK2L)
- [x] Update default theme
  - [x] Update submodule reference
- [x] Update character INIs
- [x] Merge into master and designate 2.8 tag
- [x] Windows release:
  - [x] Create final Windows artifact (CI)
  - [x] Insert vanilla content
  - [x] Insert launcher and version.ini
  - [x] Upload zip file to Wasabi
  - [x] Update launcher manifests (manually activated pipeline should take care of this)
  - [x] Update website
- [x] Linux release:
  - [x] Create final Linux artifact (CI)
  - [x] Insert vanilla content (lowercase?)
  - [x] Insert launcher and version.ini
  - [x] Upload tar file to Wasabi
  - [x] Update launcher manifests (manually activated pipeline should take care of this)
  - [x] Update website
- [ ] macOS release: 
  - [ ] Create final macOS artifact (CI)
  - [ ] Upload zip file to Wasabi
  - [x] Update website

**Comment by Crystalwarrior** [comment]
I suggest we make a Google doc with all the devs being added to it for organizing the big ass changelog of features. I'll be able to port over the changes I made from the docs I had for QA releases of the KFO client alpha,

**Comment by Crystalwarrior** [comment]
Additional feature I really want to add is more options and settings for further customization, for example an option to use the character's chat box, a specific misc folder chatbox or fallback to the current theme chatbox. This would fall in line with webao already implementing this feature and allow uses to mitigate the incredibly annoying issue of stylistic chaos that comes with per-character chat boxes (which are also sometimes really broken due to the newly introduced variable showname chat boxes system)

**Comment by stonedDiscord** [comment]
(excluding proposed changes to the character roster)
uhhhhh i did a bunch more
https://gitlab.com/AttorneyOnline/vanilla-assets/-/tree/2.8-rc

**Comment by oldmud0** [comment]
@Crystalwarrior Changelog: https://hackmd.io/@oldmud0/H1fharK2L

**Comment by oldmud0** [comment]
It looks like we have a stable client with 4bc23c889f22d8babe073a1e13693623f74261e3 (at least for Windows). 2.8 is ready for release. The only items left to package are the base and launcher.

**Comment by Crystalwarrior** [comment]
@oldmud0 it's great news that we have a release-ready version! I will look over the current release myself to perform any tweaks, bugfixes or crucial features (the chat box setting has been requested of me a lot, it would be disappointing for my users not to have it).

Additionally, I wanted to clear up the confusion about the launcher you mentioned. No support will be dropped for gif/mp3, correct? Will you be able to supply content packs with multiple file formats? Maybe a separate issue is necessary on the Launcher's GitHub?

**Comment by oldmud0** [comment]
> Additionally, I wanted to clear up the confusion about the launcher you mentioned. No support will be dropped for gif/mp3, correct? Will you be able to supply content packs with multiple file formats? Maybe a separate issue is necessary on the Launcher's GitHub?

Correct. There are no plans to drop support for GIF/MP3, and they can still be mixed at will. However, as it is proving to be messy, it would be beneficial for the client to support mounting content packs as they are, instead of merging them with the base folder.

**Comment by Crystalwarrior** [comment]
Content packs method is exactly what I've been planning for my server as well! This is going to be amazing to set up, keep me updated on everything related to the launcher so I can transition my server from the massive filedumpsterfire to a nice content pack-based system @oldmud0

**Comment by Crystalwarrior** [comment]
when

**Comment by oldmud0** [comment]
:(

**Comment by Crystalwarrior** [comment]
31st of july

**Comment by oldmud0** [comment]
yes

**Comment by oldmud0** [comment]
Released with some issues to be filed separately.
